#include <stdint.h>
#include "kernel.h"
#include "cpu.h"
#include "util.h"
#include "memory.h"
#include "terminal.h"

struct tss tss;

void initalize_tss(void) {
	uint64_t stack;

	memset(&tss, 0, sizeof(struct tss));

	stack = KERNEL_STACK_TOP;
	memcpy(&tss.rsp0, &stack, 8);
	memcpy(&tss.rsp1, &stack, 8);
	memcpy(&tss.rsp2, &stack, 8);
}

#define GDT_FLAG_PAGE_GRANULARITY 0x80
#define GDT_FLAG_DEFAULT_OPERAND_32 0x40
#define GDT_FLAG_LONG_CODE 0x20

#define GDT_TYPE_PRESENT 0x80
#define GDT_TYPE_DPL(n) (((n) & 3) << 5)
#define GDT_TYPE_NON_SYSTEM 0x10
#define GDT_TYPE_CODE 8
#define GDT_TYPE_EXPAND_DOWN 4
#define GDT_TYPE_CONFORMING 4
#define GDT_TYPE_RW 2
#define GDT_TYPE_XR 2
#define GDT_TYPE_ACCESSED 1
#define GDT_TYPE_TSS 9
#define GDT_TYPE_TSS_BUSY 2

void create_gdt_entry(gdte_t *entry, uint64_t base, uint8_t flags, uint8_t type) {
	*entry = 0;

	*entry |= (base & 0x00ffffff) << 16;
	*entry |= (base & 0xff000000) << 56;

	*entry |= (uint64_t) flags << 48;
	*entry |= (uint64_t) type << 40;
}

/*
Descriptor Map
00	Null Selector
08	Kernel Code
10	Kernel Data
18	Tss (double entry)
20	Tss (double entry)
28	User Data
30	User Code
*/
#define GDT_ENTRY_COUNT 7
gdte_t gdt[GDT_ENTRY_COUNT];
void initalize_gdt(void) {
	uint8_t type, flags;
	uint16_t limit;

	memset(&gdt[0], 0, sizeof(gdte_t));

	type = GDT_TYPE_PRESENT | GDT_TYPE_DPL(0) | GDT_TYPE_NON_SYSTEM | GDT_TYPE_CODE | GDT_TYPE_XR;
	flags = GDT_FLAG_PAGE_GRANULARITY | GDT_FLAG_LONG_CODE;
	create_gdt_entry(&gdt[1], 0, flags, type);

	type = GDT_TYPE_PRESENT | GDT_TYPE_DPL(0) | GDT_TYPE_NON_SYSTEM | GDT_TYPE_RW;
	flags = GDT_FLAG_PAGE_GRANULARITY;
	create_gdt_entry(&gdt[2], 0, flags, type);

	initalize_tss();
	type = GDT_TYPE_PRESENT | GDT_TYPE_DPL(0) | GDT_TYPE_TSS;
	flags = 0;
	create_gdt_entry(&gdt[3], (uint64_t) &tss, flags, type);
	gdt[4] = (uint64_t) &tss >> 32;

	type = GDT_TYPE_PRESENT | GDT_TYPE_DPL(3) | GDT_TYPE_NON_SYSTEM | GDT_TYPE_RW;
	flags = GDT_FLAG_PAGE_GRANULARITY;
	create_gdt_entry(&gdt[5], 0, flags, type);

	type = GDT_TYPE_PRESENT | GDT_TYPE_DPL(3) | GDT_TYPE_NON_SYSTEM | GDT_TYPE_CODE | GDT_TYPE_XR;
	flags = GDT_FLAG_PAGE_GRANULARITY | GDT_FLAG_LONG_CODE;
	create_gdt_entry(&gdt[6], 0, flags, type);

	limit = sizeof(gdte_t) * GDT_ENTRY_COUNT - 1;
	flush_gdt(&gdt[0], limit);
}

#define IDT_TYPE_PRESENT 0x8000
#define IDT_TYPE_DPL(n) (((n) & 3) << 13)
#define IDT_TYPE_CALL_GATE 0xc00
/* See Intel Manual 3 Section 6.12.1.2 on Interrupt vs Trap gates. */
/* Essentially, Interrupt gates cannot be interrupted but traps can be. */
#define IDT_TYPE_INTERRUPT_GATE 0xe00
#define IDT_TYPE_TRAP_GATE 0xf00
#define IDT_TYPE_IST(n) ((n) & 7)

void create_idt_entry(idte_t *entry, uint64_t offset, uint16_t segment, uint16_t type) {
	(*entry)[1] = offset >> 32;
	(*entry)[0] = (offset & 0xffff0000) << 32;
	(*entry)[0] |= (uint64_t) type << 32;
	(*entry)[0] |= (uint64_t) segment << 16;
	(*entry)[0] |= offset & 0xffff;
}

#define IDT_ENTRY_COUNT 256
idte_t idt[IDT_ENTRY_COUNT];
#define INSERT_IDT_STUB(n) \
	extern void idt_stub_ ## n (void); \
	create_idt_entry(&idt[n], (uint64_t) idt_stub_ ## n, 8, type);
	
void initalize_idt(void) {
	uint16_t type;
	uint16_t limit;
	size_t i;

	type = IDT_TYPE_IST(0) | IDT_TYPE_DPL(0) | IDT_TYPE_PRESENT | IDT_TYPE_TRAP_GATE;

	INSERT_IDT_STUB(0);
	INSERT_IDT_STUB(1);
	INSERT_IDT_STUB(2);
	INSERT_IDT_STUB(3);
	INSERT_IDT_STUB(4);
	INSERT_IDT_STUB(5);
	INSERT_IDT_STUB(6);
	INSERT_IDT_STUB(7);
	INSERT_IDT_STUB(8);
	INSERT_IDT_STUB(9);
	INSERT_IDT_STUB(10);
	INSERT_IDT_STUB(11);
	INSERT_IDT_STUB(12);
	INSERT_IDT_STUB(13);
	INSERT_IDT_STUB(14);
	INSERT_IDT_STUB(15);
	INSERT_IDT_STUB(16);
	INSERT_IDT_STUB(17);
	INSERT_IDT_STUB(18);
	INSERT_IDT_STUB(19);
	INSERT_IDT_STUB(20);
	INSERT_IDT_STUB(21);
	INSERT_IDT_STUB(22);
	INSERT_IDT_STUB(23);
	INSERT_IDT_STUB(24);
	INSERT_IDT_STUB(25);
	INSERT_IDT_STUB(26);
	INSERT_IDT_STUB(27);
	INSERT_IDT_STUB(28);
	INSERT_IDT_STUB(29);
	INSERT_IDT_STUB(30);
	INSERT_IDT_STUB(31);
	INSERT_IDT_STUB(32);
	INSERT_IDT_STUB(33);
	INSERT_IDT_STUB(34);
	INSERT_IDT_STUB(35);
	INSERT_IDT_STUB(36);
	INSERT_IDT_STUB(37);
	INSERT_IDT_STUB(38);
	INSERT_IDT_STUB(39);
	INSERT_IDT_STUB(40);
	INSERT_IDT_STUB(41);
	INSERT_IDT_STUB(42);
	INSERT_IDT_STUB(43);
	INSERT_IDT_STUB(44);
	INSERT_IDT_STUB(45);
	INSERT_IDT_STUB(46);
	INSERT_IDT_STUB(47);
	INSERT_IDT_STUB(48);
	INSERT_IDT_STUB(49);
	INSERT_IDT_STUB(50);
	INSERT_IDT_STUB(51);
	INSERT_IDT_STUB(52);
	INSERT_IDT_STUB(53);
	INSERT_IDT_STUB(54);
	INSERT_IDT_STUB(55);
	INSERT_IDT_STUB(56);
	INSERT_IDT_STUB(57);
	INSERT_IDT_STUB(58);
	INSERT_IDT_STUB(59);
	INSERT_IDT_STUB(60);
	INSERT_IDT_STUB(61);
	INSERT_IDT_STUB(62);
	INSERT_IDT_STUB(63);
	INSERT_IDT_STUB(64);
	INSERT_IDT_STUB(65);
	INSERT_IDT_STUB(66);
	INSERT_IDT_STUB(67);
	INSERT_IDT_STUB(68);
	INSERT_IDT_STUB(69);
	INSERT_IDT_STUB(70);
	INSERT_IDT_STUB(71);
	INSERT_IDT_STUB(72);
	INSERT_IDT_STUB(73);
	INSERT_IDT_STUB(74);
	INSERT_IDT_STUB(75);
	INSERT_IDT_STUB(76);
	INSERT_IDT_STUB(77);
	INSERT_IDT_STUB(78);
	INSERT_IDT_STUB(79);
	INSERT_IDT_STUB(80);
	INSERT_IDT_STUB(81);
	INSERT_IDT_STUB(82);
	INSERT_IDT_STUB(83);
	INSERT_IDT_STUB(84);
	INSERT_IDT_STUB(85);
	INSERT_IDT_STUB(86);
	INSERT_IDT_STUB(87);
	INSERT_IDT_STUB(88);
	INSERT_IDT_STUB(89);
	INSERT_IDT_STUB(90);
	INSERT_IDT_STUB(91);
	INSERT_IDT_STUB(92);
	INSERT_IDT_STUB(93);
	INSERT_IDT_STUB(94);
	INSERT_IDT_STUB(95);
	INSERT_IDT_STUB(96);
	INSERT_IDT_STUB(97);
	INSERT_IDT_STUB(98);
	INSERT_IDT_STUB(99);
	INSERT_IDT_STUB(100);
	INSERT_IDT_STUB(101);
	INSERT_IDT_STUB(102);
	INSERT_IDT_STUB(103);
	INSERT_IDT_STUB(104);
	INSERT_IDT_STUB(105);
	INSERT_IDT_STUB(106);
	INSERT_IDT_STUB(107);
	INSERT_IDT_STUB(108);
	INSERT_IDT_STUB(109);
	INSERT_IDT_STUB(110);
	INSERT_IDT_STUB(111);
	INSERT_IDT_STUB(112);
	INSERT_IDT_STUB(113);
	INSERT_IDT_STUB(114);
	INSERT_IDT_STUB(115);
	INSERT_IDT_STUB(116);
	INSERT_IDT_STUB(117);
	INSERT_IDT_STUB(118);
	INSERT_IDT_STUB(119);
	INSERT_IDT_STUB(120);
	INSERT_IDT_STUB(121);
	INSERT_IDT_STUB(122);
	INSERT_IDT_STUB(123);
	INSERT_IDT_STUB(124);
	INSERT_IDT_STUB(125);
	INSERT_IDT_STUB(126);
	INSERT_IDT_STUB(127);
	INSERT_IDT_STUB(128);
	INSERT_IDT_STUB(129);
	INSERT_IDT_STUB(130);
	INSERT_IDT_STUB(131);
	INSERT_IDT_STUB(132);
	INSERT_IDT_STUB(133);
	INSERT_IDT_STUB(134);
	INSERT_IDT_STUB(135);
	INSERT_IDT_STUB(136);
	INSERT_IDT_STUB(137);
	INSERT_IDT_STUB(138);
	INSERT_IDT_STUB(139);
	INSERT_IDT_STUB(140);
	INSERT_IDT_STUB(141);
	INSERT_IDT_STUB(142);
	INSERT_IDT_STUB(143);
	INSERT_IDT_STUB(144);
	INSERT_IDT_STUB(145);
	INSERT_IDT_STUB(146);
	INSERT_IDT_STUB(147);
	INSERT_IDT_STUB(148);
	INSERT_IDT_STUB(149);
	INSERT_IDT_STUB(150);
	INSERT_IDT_STUB(151);
	INSERT_IDT_STUB(152);
	INSERT_IDT_STUB(153);
	INSERT_IDT_STUB(154);
	INSERT_IDT_STUB(155);
	INSERT_IDT_STUB(156);
	INSERT_IDT_STUB(157);
	INSERT_IDT_STUB(158);
	INSERT_IDT_STUB(159);
	INSERT_IDT_STUB(160);
	INSERT_IDT_STUB(161);
	INSERT_IDT_STUB(162);
	INSERT_IDT_STUB(163);
	INSERT_IDT_STUB(164);
	INSERT_IDT_STUB(165);
	INSERT_IDT_STUB(166);
	INSERT_IDT_STUB(167);
	INSERT_IDT_STUB(168);
	INSERT_IDT_STUB(169);
	INSERT_IDT_STUB(170);
	INSERT_IDT_STUB(171);
	INSERT_IDT_STUB(172);
	INSERT_IDT_STUB(173);
	INSERT_IDT_STUB(174);
	INSERT_IDT_STUB(175);
	INSERT_IDT_STUB(176);
	INSERT_IDT_STUB(177);
	INSERT_IDT_STUB(178);
	INSERT_IDT_STUB(179);
	INSERT_IDT_STUB(180);
	INSERT_IDT_STUB(181);
	INSERT_IDT_STUB(182);
	INSERT_IDT_STUB(183);
	INSERT_IDT_STUB(184);
	INSERT_IDT_STUB(185);
	INSERT_IDT_STUB(186);
	INSERT_IDT_STUB(187);
	INSERT_IDT_STUB(188);
	INSERT_IDT_STUB(189);
	INSERT_IDT_STUB(190);
	INSERT_IDT_STUB(191);
	INSERT_IDT_STUB(192);
	INSERT_IDT_STUB(193);
	INSERT_IDT_STUB(194);
	INSERT_IDT_STUB(195);
	INSERT_IDT_STUB(196);
	INSERT_IDT_STUB(197);
	INSERT_IDT_STUB(198);
	INSERT_IDT_STUB(199);
	INSERT_IDT_STUB(200);
	INSERT_IDT_STUB(201);
	INSERT_IDT_STUB(202);
	INSERT_IDT_STUB(203);
	INSERT_IDT_STUB(204);
	INSERT_IDT_STUB(205);
	INSERT_IDT_STUB(206);
	INSERT_IDT_STUB(207);
	INSERT_IDT_STUB(208);
	INSERT_IDT_STUB(209);
	INSERT_IDT_STUB(210);
	INSERT_IDT_STUB(211);
	INSERT_IDT_STUB(212);
	INSERT_IDT_STUB(213);
	INSERT_IDT_STUB(214);
	INSERT_IDT_STUB(215);
	INSERT_IDT_STUB(216);
	INSERT_IDT_STUB(217);
	INSERT_IDT_STUB(218);
	INSERT_IDT_STUB(219);
	INSERT_IDT_STUB(220);
	INSERT_IDT_STUB(221);
	INSERT_IDT_STUB(222);
	INSERT_IDT_STUB(223);
	INSERT_IDT_STUB(224);
	INSERT_IDT_STUB(225);
	INSERT_IDT_STUB(226);
	INSERT_IDT_STUB(227);
	INSERT_IDT_STUB(228);
	INSERT_IDT_STUB(229);
	INSERT_IDT_STUB(230);
	INSERT_IDT_STUB(231);
	INSERT_IDT_STUB(232);
	INSERT_IDT_STUB(233);
	INSERT_IDT_STUB(234);
	INSERT_IDT_STUB(235);
	INSERT_IDT_STUB(236);
	INSERT_IDT_STUB(237);
	INSERT_IDT_STUB(238);
	INSERT_IDT_STUB(239);
	INSERT_IDT_STUB(240);
	INSERT_IDT_STUB(241);
	INSERT_IDT_STUB(242);
	INSERT_IDT_STUB(243);
	INSERT_IDT_STUB(244);
	INSERT_IDT_STUB(245);
	INSERT_IDT_STUB(246);
	INSERT_IDT_STUB(247);
	INSERT_IDT_STUB(248);
	INSERT_IDT_STUB(249);
	INSERT_IDT_STUB(250);
	INSERT_IDT_STUB(251);
	INSERT_IDT_STUB(252);
	INSERT_IDT_STUB(253);
	INSERT_IDT_STUB(254);
	INSERT_IDT_STUB(255);

	limit = sizeof(idte_t) * IDT_ENTRY_COUNT - 1;
	load_idt(&idt[0], limit);
}
